[workspace]
members = [
    "lc_18",
    "lc_34",
    "lc_35",
    "lc_41",
    "lc_82",
    "lc_98",
    "lc_144",
    "lc_725",
    "lc_1201",
    "lc_1282",
    "lc_1437",
    "lc_1742",
    "lc_1998"
]