[package]
name = "lc_1742"
version = "0.1.0"
authors = ["fengyingcai <fengyc.work@gmail.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
